-- Bufferline configuration
-- return {
-- 	"akinsho/bufferline.nvim",
-- 	dependencies = { "nvim-tree/nvim-web-devicons" },
-- 	version = "*",
-- 	opts = {
-- 	    options = {
-- 	        mode = "tabs", -- This enables tab mode
-- 	        -- separator_style = "slant",
-- 	        offsets = {
-- 	            {
-- 	                filetype = "NvimTree",
-- 	                text = "File Explorer",
-- 	                highlight = "Directory",
-- 	                -- separator = true, -- use a "true" to enable the default, or set your own character
-- 	            },
-- 	        },
-- 	        custom_areas = {
-- 	            right = function()
-- 	                return {
-- 	                    { text = " ", highlight = "BufferLineFill" },
-- 	                }
-- 	            end,
-- 	        },
-- 	    },
-- 	},
-- 	config = function(_, opts)
-- 	    require("bufferline").setup(opts)
--
-- 	    -- Set up the keymaps
-- 	    local keymap = vim.keymap
--
-- 	    -- tabs management
-- 	    keymap.set("n", "<leader>to", "<cmd>tabnew<CR>", { desc = "Open new tab" })
-- 	    keymap.set("n", "<leader>tx", "<cmd>BufferLineCloseOther<CR>", { desc = "Close other tabs" })
-- 	    keymap.set("n", "<leader>tn", "<cmd>BufferLineCycleNext<CR>", { desc = "Go to next tab" })
-- 	    keymap.set("n", "<leader>tp", "<cmd>BufferLineCyclePrev<CR>", { desc = "Go to previous tab" })
-- 	    keymap.set("n", "<leader>tf", "<cmd>tab split<CR>", { desc = "Open current buffer in new tab" })
-- 	end,
-- }
return {}
