return {
    -- "j-hui/fidget.nvim",
    -- event = "LspAttach",
    -- opts = {
    --     progress = {
    --         display = {
    --             done_icon = "✔",
    --             spinner = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
    --         },
    --     },
    --     notification = {
    --         override_vim_notify = false,
    --     },
    --     window = {
    --         winblend = 0, -- make it opaque
    --         normal_hl = "Comment",
    --     },
    -- },
    -- config = function(_, opts)
    --     require("fidget").setup(opts)
    --
    --     -- Apply custom UI colors
    --     vim.api.nvim_set_hl(0, "FidgetTitle", { fg = "#505050" })
    --     vim.api.nvim_set_hl(0, "FidgetTask", { fg = "#505050" })
    -- end,
}
