-- return {
-- 	"echasnovski/mini.animate",
-- 	version = "*",
-- 	config = function()
-- 		local animate = require("mini.animate")
-- 		animate.setup({
-- 			-- Cursor path
-- 			cursor = {
-- 				enable = true,
-- 				timing = function(dur)
-- 					return math.min(dur * 1.5, 150)
-- 				end,
-- 				-- Use the predefined path generator
-- 				path = animate.gen_path.line(),
-- 			},
-- 			-- Smooth scroll
-- 			scroll = {
-- 				enable = true,
-- 				timing = function(dur)
-- 					return math.min(dur * 1.5, 150)
-- 				end,
-- 				subscroll = animate.gen_subscroll.equal({
-- 					predicate = function()
-- 						return true
-- 					end,
-- 				}),
-- 			},
-- 			-- Smooth resize
-- 			resize = {
-- 				enable = true,
-- 				timing = function(dur)
-- 					return math.min(dur * 1.5, 100)
-- 				end,
-- 			},
-- 			-- Smooth open/close windows
-- 			open = {
-- 				enable = true,
-- 				timing = function(dur)
-- 					return math.min(dur * 1.5, 100)
-- 				end,
-- 			},
-- 			close = {
-- 				enable = true,
-- 				timing = function(dur)
-- 					return math.min(dur * 1.5, 100)
-- 				end,
-- 			},
-- 		})
-- 	end,
-- }
return {}
