return {
    -- "folke/noice.nvim",
    -- event = "VeryLazy",
    -- opts = {
    --     cmdline = {
    --         enabled = true,
    --         -- view = "cmdline",
    --         opts = { buf_options = { filetype = "vim" } },
    --     },
    --     messages = {
    --         enabled = true,
    --         view = "notify",
    --     },
    -- },
    -- dependencies = {
    --     "MunifTanjim/nui.nvim",
    --     {
    --         "rcarriga/nvim-notify",
    --         opts = {
    --             background_colour = "#000000", -- You can adjust this color to match your theme
    --         },
    --     },
    -- },
}
