return {
    -- "gelguy/wilder.nvim",
    -- config = function()
    --     local wilder = require("wilder")
    --     wilder.setup({
    --         modes = { ":", "/", "?" }, -- Enable wilder for command-line and search modes
    --     })
    --
    --     wilder.set_option(
    --         "renderer",
    --         wilder.popupmenu_renderer({
    --             highlighter = wilder.basic_highlighter(),
    --             left = { " ", wilder.popupmenu_devicons() },
    --             right = { " ", wilder.popupmenu_scrollbar() },
    --         })
    --     )
    -- end,
    -- dependencies = {
    --     { "romgrk/fzy-lua-native", build = "make" }, -- Optional for better performance
    -- },
}
