-- custom_theme.lua

local M = {}
--
-- -- Define your color palette
-- local colors = {
--     bg = "#0e0e0e",
--     fg = "#ffffff",
--     red = "#ff0000",
--     green = "#00ff00",
--     blue = "#0000ff",
--     yellow = "#ffff00",
--     purple = "#800080",
--     cyan = "#00ffff",
--     orange = "#ffa500",
--     gray = "#808080",
--     -- Add more colors as needed
-- }
--
-- function M.setup()
--     -- Clear existing highlights
--     vim.cmd("highlight clear")
--
--     -- Set the background
--     vim.o.background = "dark" -- or "light" if you prefer
--
--     -- Set colorscheme name
--     vim.g.colors_name = "custom-theme"
--
--     -- Define highlight groups
--     local highlights = {
--         -- UI elements
--         Normal = { fg = colors.fg, bg = colors.bg },
--         LineNr = { fg = colors.gray },
--         CursorLine = { bg = colors.bg },
--         CursorLineNr = { fg = colors.yellow },
--         StatusLine = { fg = colors.fg, bg = colors.gray },
--
--         -- Syntax groups
--         Comment = { fg = colors.gray, italic = true },
--         Constant = { fg = colors.purple },
--         String = { fg = colors.green },
--         Identifier = { fg = colors.blue },
--         Function = { fg = colors.yellow },
--         Statement = { fg = colors.red },
--         PreProc = { fg = colors.cyan },
--         Type = { fg = colors.blue },
--         Special = { fg = colors.orange },
--
--         -- Add more highlight groups as needed
--     }
--
--     -- Set highlights
--     for group, settings in pairs(highlights) do
--         vim.api.nvim_set_hl(0, group, settings)
--     end
-- end
--
-- return
